version: '3.8'
services:
  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: .
      target: dev_nginx
      args:
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        PROJECT_URI: ${PROJECT_URI}
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - $HTTP_PORT:80
    volumes:
      - ../..:/var/www/html
      - ./volumes/logs/nginx:/var/log/nginx

  phpfpm:
    build:
      dockerfile: ./phpfpm/Dockerfile
      context: .
      target: dev_phpfpm
    container_name: ${COMPOSE_PROJECT_NAME}_phpfpm
    volumes:
      - ../..:/var/www/html
      - ~/.composer/cache:/home/local/.composer/cache

  nodejs:
    build:
      dockerfile: ./nodejs/Dockerfile
      context: .
      target: dev_nodejs
    container_name: ${COMPOSE_PROJECT_NAME}_nodejs
    volumes:
      - ../..:/home/node/app
    command: sleep infinity

  mysql:
    build:
      dockerfile: ./mysql/Dockerfile
      context: .
      target: dev_mysql
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/databases:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${COMPOSE_PROJECT_NAME}
      MYSQL_PASSWORD: ${COMPOSE_PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: root
